version: '1.0.{build}'
image: Visual Studio 2022
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./owasp4net.injection/owasp4net.injection.csproj --verbosity m
build_script:
  # output will be in ./bin/release/net6.0/publish
  - cmd: dotnet publish -c Release ./owasp4net.injection/owasp4net.injection.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: 'owasp4net.injection\bin\Release\net6.0\publish\'
   name: WebSite
   type: WebDeployPackage  
clone_depth: 1
test_script:
  # restore packages for our unit tests
  # run the unit tests (requires changing into the test directory)
on_finish :
  # any cleanup in here
deploy: off
